/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#b21e61",
        "on-primary": "#ffffff",
        "primary-container": "#ff5e9c",
        "on-primary-container": "#660033",
        "inverse-primary": "#ffb1c7",
        "secondary": "#9b3f5a",
        "on-secondary": "#ffffff",
        "secondary-container": "#ff8fab",
        "on-secondary-container": "#79243f",
        "tertiary": "#755664",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#b38f9f",
        "on-tertiary-container": "#432936",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "background": "#f8f9ff",
        "on-background": "#121c2a",
        "surface": "#f8f9ff",
        "on-surface": "#121c2a",
        "surface-variant": "#d9e3f6",
        "on-surface-variant": "#584147",
        "outline": "#8b7077",
        "outline-variant": "#debec6",
        "inverse-surface": "#27313f",
        "inverse-on-surface": "#eaf1ff",
        "surface-tint": "#b21e61",
        "surface-bright": "#f8f9ff",
        "surface-dim": "#d0dbed",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e6eeff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "primary-fixed": "#ffd9e2",
        "primary-fixed-dim": "#ffb1c7",
        "on-primary-fixed": "#3e001d",
        "on-primary-fixed-variant": "#8e0049",
        "secondary-fixed": "#ffd9e0",
        "secondary-fixed-dim": "#ffb1c2",
        "on-secondary-fixed": "#3f0018",
        "on-secondary-fixed-variant": "#7d2742",
        "tertiary-fixed": "#ffd8e8",
        "tertiary-fixed-dim": "#e3bccc",
        "on-tertiary-fixed": "#2b1420",
        "on-tertiary-fixed-variant": "#5b3e4c"
      },
      borderRadius: {
        "DEFAULT": "0.5rem",
        "sm": "0.25rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "12px",
        "base": "16px",
        "lg": "24px",
        "xl": "32px",
        "2xl": "40px",
        "3xl": "48px",
        "4xl": "64px"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "caption": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "h1": ["Inter", "sans-serif"],
        "h1-mobile": ["Inter", "sans-serif"],
        "h2": ["Inter", "sans-serif"],
        "h3": ["Inter", "sans-serif"],
        "handwriting": ["Dancing Script", "cursive"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "caption": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "h1-mobile": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "h2": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "h3": ["20px", { lineHeight: "28px", fontWeight: "600" }]
      }
    },
  },
  plugins: [],
}
